name: Release to Production Environment
on:
  push:
    branches:
      - master

jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master # １
        with: # ２ アクションの入力パラメータを指定
          host: ${{ secrets.SSH_HOST }} # ホスト名
          username: ${{ secrets.SSH_USERNAME }} # SSH ユーザ名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 秘密鍵の内容
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # 秘密鍵のパスフレーズ
          port: ${{ secrets.SSH_PORT }} # ポート番号
          script: |
            cd /opt/disbot1
            git switch bot_product
            git pull origin master
            sudo systemctl daemon-reload
            sudo systemctl restart disbot1
